

services:
  frontend:
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - BACKEND_URL= http://backend-app-lb-1551102113.us-east-1.elb.amazonaws.com  # Add your backend URL here