name: Manual Build Image

on:
  workflow_dispatch:


jobs:
  build_image:
    name: Build Image and deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build Docker Image
        run: |
          docker compose build

          docker tag cloudslaves-frontend ${{ secrets.DOCKER_HUB_USERNAME }}/cloudslaves-frontend:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cloudslaves-frontend:latest
          





