name: TF Destroy

on:
  workflow_dispatch:


jobs:
  build_image:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .json file
        run: |
          echo '{
            "access_key": "${{ secrets.ACCESS_KEY }}",
            "secret_key": "${{ secrets.SECRET_KEY }}"
          }' > terraform/credentials.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version:  1.8.2
      
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve